# Generated by Django 5.2 on 2025-05-25 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_activityprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('media_file', models.FileField(upload_to='media_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.childprofile')),
            ],
        ),
    ]
