# Generated by Django 5.2 on 2025-06-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_photoreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediareport',
            name='description',
        ),
        migrations.AddField(
            model_name='mediareport',
            name='activity_name',
            field=models.CharField(default='نامشخص', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediareport',
            name='media_type',
            field=models.CharField(choices=[('video', 'ویدئو'), ('image', 'تصویر')], max_length=10),
        ),
    ]
