# Generated by Django 5.2 on 2025-06-08 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_weeklytopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='موضوع')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.childprofile')),
            ],
        ),
    ]
