# Generated by Django 5.2 on 2025-06-16 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_foodschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindergartenClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='childprofile',
            name='kindergarten_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kindergartenclass'),
        ),
    ]
