# Generated by Django 5.2 on 2025-06-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_kindergartenclass_childprofile_kindergarten_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediareport',
            name='activity_name',
        ),
        migrations.RemoveField(
            model_name='mediareport',
            name='child',
        ),
        migrations.RemoveField(
            model_name='mediareport',
            name='created_at',
        ),
        migrations.AddField(
            model_name='mediareport',
            name='date',
            field=models.DateField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediareport',
            name='kindergarten_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.kindergartenclass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediareport',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
