# Generated by Django 5.2 on 2025-06-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_mediareport_activity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityprogress',
            name='activity_name',
            field=models.CharField(choices=[('یوگا', 'یوگا'), ('زبان عمومی', 'زبان عمومی'), ('باغبانی', 'باغبانی'), ('آشپزی', 'آشپزی'), ('قصه خوانی', 'قصه خوانی'), ('سرود خوانی', 'سرود خوانی'), ('بارش افکار', 'بارش افکار'), ('بازی', 'بازی'), ('نقاشی', 'نقاشی'), ('آداب اجتماعی', 'آداب اجتماعی'), ('قانونمندی', 'قانونمندی'), ('نخ کردنی', 'نخ کردنی'), ('مفاهیم علوم', 'مفاهیم علوم'), ('کارگاه سفال', 'کارگاه سفال'), ('مفاهیم ریاضی', 'مفاهیم ریاضی'), ('کارگاه چاپ', 'کارگاه چاپ'), ('کاردستی', 'کاردستی'), ('نمایش خلاق', 'نمایش خلاق')], max_length=50),
        ),
    ]
